apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: traceapp-svc-monitor
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      apps: sb-trace
  endpoints:
  - port: metrics-port