apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-conf-cm
  labels:
    app: fluentd-conf-webapp
data:
  fluent.conf: |
      <source>
        @type tail
        format none
        path /tmp/application.log
        pos_file positions.pos
        tag webapp.*
        path_key filename
      </source>

      <match webapp.**>
        @type loki
        url "http://loki:3100"
        flush_interval 1s
        flush_at_shutdown true
        buffer_chunk_limit 1m
        extra_labels {"job":"fluentd-webapplogs", "agent":"fluentd"}
        <label>
            filename
        </label>
      </match>
